# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Easton Lee
email: me@eastonlee.com
#description: > # this means to ignore newlines until "baseurl:"
description: "This is Easton Lee's personal site where he places his thoughts into words and records his achievements."
baseurl:  # the subpath of your site, e.g. /blog
url: http://eastonlee.com # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: eastonlee.com
twitter_username: EastonLeeCS
github_username:  EastonLee
linkedin_username:  EastonLee
# logo is for BlogPosting > publisher > logo > url schemas.
logo: https://eastonlee.b0.upaiyun.com/organization_logo.png
# setting image fixed for SEO is not sensible
# image is for BlogPosting > image schemas.
defaults:
  - 
    scope:
      path: ""
      type: "post"
    values:
      image: 
        "@type": ImageObject
        path: https://eastonlee.b0.upaiyun.com/avatar.jpg
        height: 1000
        width: 1000  

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

safe: false

# easton
permalink: /blog/:year/:month/:day/:title/

# minima theme, deprecated
show_downloads: false
google_analytics: UA-58961104-2

# poole theme, being used, just need to modify font-size in _variables.scss
#html {
#  font-size: 14px;
#  line-height: 1.5;
#}
#@media (min-width: 38em) {
#  html {
#    font-size: 20px;
#  }
#}
tagline: experientialism
paginate:            1
sass:
  sass_dir:          _sass
  style:            :compressed
author: Easton Lee

analytics_id: UA-58961104-2

disqus:
  shortname: eastonlee

excerpt_separator: <!--more-->
