# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EastonLee
email: me@eastonlee.com
description: > # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog
url: http://eastonlee.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  easton042
linkedin_username:  eastonlee

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

safe: false

# easton
permalink: /blog/:year/:month/:day/:title/

# minima theme, deprecated
show_downloads: false
google_analytics: UA-58961104-2

# poole theme, being used, just need to modify font-size in _variables.scss
#html {
#  font-size: 14px;
#  line-height: 1.5;
#}
#@media (min-width: 38em) {
#  html {
#    font-size: 20px;
#  }
#}
tagline: experientialism
paginate:            1
sass:
  sass_dir:          _sass
  style:            :compressed
author: Easton Lee

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
analytics_id: UA-58961104-2

disqus:
  shortname: eastonlee